package LearnJava.Java8Features.Lambda;

import java.io.Serializable;
import java.util.function.Consumer;
import java.util.function.Function;

/**
 * Created by qimingzhang on 2017/5/2.
 */
public class Lambda {
    @FunctionalInterface
    interface LambdaInterface{
        void method();
    }
    public static void main(String[] args) {
        Consumer consumer =  (value) -> System.out.println("I 'm a lambda expression of consumer!");
        consumer.accept(1);
        Function<?, ?> function = (String value) -> System.out.printf("%s%n",value);
        function = (value) -> System.out.printf("%s%n", value);
        function = value -> System.out.printf("%s%n", value);
        LambdaInterface voidFunction = () -> System.out.println("I'm a functional interface! I'm " +
                "generated by using Lambda expression");
        voidFunction.method();
    }
}
